root -q -b 'examples/AfbUnfoldTests2D.cxx+(0,"Linearity",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(1,"Linearity",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(2,"Linearity",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(3,"Linearity",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(4,"Linearity",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(5,"Linearity",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(6,"Linearity",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(7,"Linearity",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(8,"Linearity",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(9,"Linearity",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(10,"Linearity",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(11,"Linearity",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(0,"Linearity",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(1,"Linearity",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(2,"Linearity",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(3,"Linearity",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(4,"Linearity",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(5,"Linearity",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(6,"Linearity",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(7,"Linearity",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(8,"Linearity",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(9,"Linearity",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(10,"Linearity",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(11,"Linearity",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(0,"Linearity",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(1,"Linearity",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(2,"Linearity",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(3,"Linearity",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(4,"Linearity",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(5,"Linearity",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(6,"Linearity",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(7,"Linearity",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(8,"Linearity",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(9,"Linearity",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(10,"Linearity",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(11,"Linearity",0,"ttrapidity2")' &
