root -q -b 'examples/AfbUnfoldTests2D.cxx+(0,"Pull",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(1,"Pull",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(2,"Pull",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(3,"Pull",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(4,"Pull",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(5,"Pull",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(6,"Pull",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(7,"Pull",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(8,"Pull",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(9,"Pull",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(10,"Pull",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(11,"Pull",0,"mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(0,"Pull",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(1,"Pull",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(2,"Pull",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(3,"Pull",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(4,"Pull",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(5,"Pull",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(6,"Pull",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(7,"Pull",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(8,"Pull",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(9,"Pull",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(10,"Pull",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(11,"Pull",0,"ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(0,"Pull",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(1,"Pull",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(2,"Pull",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(3,"Pull",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(4,"Pull",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(5,"Pull",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(6,"Pull",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(7,"Pull",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(8,"Pull",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(9,"Pull",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(10,"Pull",0,"ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx+(11,"Pull",0,"ttrapidity2")' &
